version: '2'
services:
    toodo-app:
        image: toodo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://toodo-postgresql:5432/toodo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    toodo-postgresql:
        extends:
            file: postgresql.yml
            service: toodo-postgresql
