version: '2'
services:
    toodo-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/toodo/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=toodo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
